# Generated by Django 3.1.7 on 2021-03-08 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('om_azonosito', models.IntegerField()),
                ('nev', models.CharField(max_length=100)),
                ('tagozat', models.CharField(max_length=2)),
                ('dontes', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
