# Generated by Django 3.1.7 on 2021-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('om_azonosito', models.CharField(max_length=11)),
                ('nev', models.CharField(max_length=100)),
                ('tagozat', models.CharField(max_length=2)),
                ('dontes', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Elem',
                'verbose_name_plural': 'Lista',
                'ordering': ['-date'],
            },
        ),
    ]
