# Generated by Django 3.1.7 on 2021-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felvettekapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['-date'], 'verbose_name': 'Elem', 'verbose_name_plural': 'Lista'},
        ),
        migrations.AlterField(
            model_name='lista',
            name='om_azonosito',
            field=models.CharField(max_length=11),
        ),
    ]
