# Generated by Django 3.1.7 on 2021-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felvettekapp', '0002_auto_20210309_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.CharField(default='eaec27e317b247d7baa7a7a42f7d6267', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
