# Generated by Django 3.1.7 on 2021-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felvettekapp', '0003_auto_20210309_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.CharField(default='81144df708f946faa001798b770089d2', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
